export const GET_ADDRESS_LIST_WATCHER = 'GET_ADDRESS_LIST_WATCHER';
export const FILL_ADDRESS_LIST = 'FILL_ADDRESS_LIST';
export const CREATE_CONTACT_WATCHER = 'CREATE_CONTACT_WATCHER';
export const UPDATE_CONTACT_WATCHER = 'UPDATE_CONTACT_WATCHER';
export const REMOVE_CONTACT_WATCHER = 'REMOVE_CONTACT_WATCHER';
export const CHANGED_FILTER_LIST = 'CHANGED_FILTER_LIST';
